export const API_CONFIG = {
  gatewayBaseUrl: 'http://localhost:8001',
  services: {
    organization: 'api-organization'
  }
} as const;

export const API_ENDPOINTS = {
  group: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/group`,
  country: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/country`,
  state: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/state`,
  city: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/city`,
  commune: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/commune`,
  schoolTypes: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/reference-data/school-types`,
  school: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/school`,
  academicModel: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/academic-model`,
  academicCycle: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/academic-cycle`,
  academicLevel: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/academic-level`,
  academicSection: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/academic-section`,
  academicOption: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/academic-option`,
  subject: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/subject`,
  subjectDomain: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/subject-domain`,
  subjectSubDomain: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/subject-sub-domain`,
  academicPeriod: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/academic-period`,
  academicTerm: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/academic-term`,
  academicCurriculum: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/academic-curriculum`,
  academicCurriculumSubject: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/academic-curriculum-subject`,
  schoolAcademicModel: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/school-academic-model`,
  academicYear: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/academic-year`,
  schoolAcademicYear: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/school-academic-year`,
  schoolClass: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/school-class`,
  classroom: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/classroom`,
  classroomDesignation: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/classroom-designation`,
  studentCategory: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/student-category`,
  feeCategory: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/fee-category`,
  paymentInstallment: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/payment-installment`,
  academicFee: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/academic-fee`,
  payment: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/payment`,
  currency: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/currency`,
  schoolCurrency: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/school-currency`,
  currencyRate: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/currency-rate`,
  guardian: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/guardian`,
  enrollment: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/enrollment`,
  studentGrade: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/student-grade`,
  securityModule: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/security-module`,
  feature: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/feature`,
  role: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/role`,
  roleFeature: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/role-feature`,
  user: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/user`,
  teachers: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/teachers`,
  teacherClassAssignments: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/teacher-class-assignments`,
  teacherCourseAssignments: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/teacher-course-assignments`,
  auth: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/auth`,
  bulletinReport: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/report/bulletins`,
  enrollmentReport: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/enrollment-report`,
  paymentReceiptReport: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/report/payment-receipt`,
  paymentJournalReport: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/report/payment-journal`,
  paymentRecoveryReport: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/report/payment-recovery/dashboard`,
  configuredFeesReport: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/report/configured-fees`,
  revenueStatementReport: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/report/revenue-statement`,
  financeDashboard: `${API_CONFIG.gatewayBaseUrl}/${API_CONFIG.services.organization}/finance/dashboard`
} as const;
